server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/Users/nonoro/db/3p/wallet # 규정
#    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/Users/jy/Desktop/edu/Wallet_jambo # 종영
#    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/Users/anhyogyeong/Edu/Wallet_jambo # 효경
#    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/Users/kent/db/Wallet_jambo # 연아
#    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/Users/dyrlqhffo/Edu/Wallet_jambo # 용식
    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: ADMIN
#    password: Jambo123456!
    username: scott
    password: TIGER
  jpa:
    hibernate:
      ddl-auto:
#    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org:
      hibernate: info

