server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@jambo_medium?TNS_ADMIN=/home/ec2-user/oracle_wallet
    username: ADMIN
    password: Jambo123456!

file:
  urlPath: /img
  path: /home/ec2-user/img/
