server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE

    username: scott
    password: TIGER
  jpa:
    hibernate:
      ddl-auto:
#    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    org:
      hibernate: info

file:
  urlPath: /icon
  path: /Users/nonoro/finalJambo/projectJambo/src/main/resources/img/
